import type { ArchitectQuestion } from './types';

export const ARCHITECT_QUESTIONS: ArchitectQuestion[] = [
  {
    id: 'appIdea',
    label: 'What are you building?',
    description: 'Describe the product, tool, dashboard, marketplace, game, or workflow.',
    type: 'textarea',
    category: 'foundation',
    placeholder: 'Example: A personal CRM for tracking contacts, follow-ups, and deals.',
  },
  {
    id: 'investmentLevel',
    label: 'How much do you want to invest right now?',
    description:
      'This helps the Architect recommend free-first, managed, or scale-ready services.',
    type: 'select',
    category: 'foundation',
    options: [
      {
        id: 'free-first',
        label: 'Free-first / prototype',
        description: 'Keep launch costs near zero and use local/demo-friendly tools.',
      },
      {
        id: 'lean',
        label: 'Lean startup',
        description: 'Use free tiers and low-cost services where they unlock real value.',
      },
      {
        id: 'professional',
        label: 'Professional product',
        description: 'Use managed services for reliability, auth, deployment, and data.',
      },
      {
        id: 'growth',
        label: 'Growth / scale',
        description: 'Plan for teams, scale, monitoring, paid features, and operations.',
      },
    ],
  },
  {
    id: 'primaryUsers',
    label: 'Who are the users?',
    description: 'Name the main people or teams who will use this app.',
    type: 'text',
    category: 'users',
    placeholder: 'Example: solo founders, sales teams, coaches, store managers',
  },
  {
    id: 'accountsRequired',
    label: 'Do users need accounts?',
    description: 'Accounts usually imply authentication, user profiles, and persistent data.',
    type: 'boolean',
    category: 'users',
  },
  {
    id: 'adminPanel',
    label: 'Does it need an admin panel?',
    description: 'Admin panels are useful for managing users, content, products, or settings.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'mobileSupport',
    label: 'Mobile support',
    description: 'Choose the mobile targets this app should consider.',
    type: 'multiselect',
    category: 'delivery',
    options: [
      { id: 'responsive-web', label: 'Responsive web' },
      { id: 'mobile-first', label: 'Mobile-first UI' },
      { id: 'android-capacitor', label: 'Future Android / Capacitor' },
      { id: 'offline-mobile', label: 'Offline mobile mode' },
    ],
  },
  {
    id: 'payments',
    label: 'Will it need payments?',
    description: 'Payments can include subscriptions, checkout, invoices, or paid plans.',
    type: 'boolean',
    category: 'integrations',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Pick the notification channels the app may need.',
    type: 'multiselect',
    category: 'integrations',
    options: [
      { id: 'in-app', label: 'In-app notifications' },
      { id: 'email', label: 'Email notifications' },
      { id: 'push', label: 'Push notifications' },
      { id: 'sms', label: 'SMS reminders' },
    ],
  },
  {
    id: 'aiFeatures',
    label: 'AI features',
    description: 'Select any AI-style capabilities the product should plan for.',
    type: 'multiselect',
    category: 'product',
    options: [
      { id: 'assistant', label: 'AI assistant' },
      { id: 'summaries', label: 'Smart summaries' },
      { id: 'recommendations', label: 'Recommendations' },
      { id: 'search', label: 'Natural-language search' },
      { id: 'content-generation', label: 'Content generation' },
    ],
  },
  {
    id: 'offlineSupport',
    label: 'Offline support',
    description: 'Useful for local-first tools, field apps, mobile workflows, and demos.',
    type: 'boolean',
    category: 'data',
  },
  {
    id: 'database',
    label: 'Data storage',
    description: 'Choose the data direction for the first version.',
    type: 'select',
    category: 'data',
    options: [
      { id: 'local-first', label: 'Local-first' },
      { id: 'cloud-database', label: 'Cloud database' },
      { id: 'hybrid', label: 'Local demo + cloud-ready' },
    ],
  },
  {
    id: 'publicWebsite',
    label: 'Public website',
    description: 'A public marketing/home page can introduce the app before sign-in.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    description: 'Dashboards summarize metrics, actions, and recent activity.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'crm',
    label: 'CRM-style workflows',
    description: 'Contacts, companies, leads, tasks, pipeline, or relationship tracking.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'scheduling',
    label: 'Scheduling',
    description: 'Appointments, bookings, reminders, calendar, or availability.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    description: 'Charts, metrics, reporting, trends, and performance views.',
    type: 'boolean',
    category: 'product',
  },
  {
    id: 'auth',
    label: 'Authentication',
    description: 'Choose how users should access the app.',
    type: 'select',
    category: 'users',
    options: [
      { id: 'none', label: 'No auth for V1' },
      { id: 'basic', label: 'Basic accounts' },
      { id: 'roles', label: 'Accounts with roles' },
      { id: 'teams', label: 'Teams / organizations' },
    ],
  },
  {
    id: 'deploymentTarget',
    label: 'Deployment target',
    description: 'Pick the intended release path.',
    type: 'select',
    category: 'delivery',
    options: [
      { id: 'nextjs-web', label: 'Next.js web app' },
      { id: 'vercel', label: 'Vercel' },
      { id: 'zip-export', label: 'ZIP export' },
      { id: 'android-later', label: 'Android later' },
    ],
  },
  {
    id: 'integrations',
    label: 'Third-party integrations',
    description: 'Select likely external services or capabilities.',
    type: 'multiselect',
    category: 'integrations',
    options: [
      { id: 'stripe', label: 'Stripe' },
      { id: 'supabase', label: 'Supabase' },
      { id: 'openai', label: 'OpenAI' },
      { id: 'resend', label: 'Resend' },
      { id: 'maps', label: 'Maps' },
      { id: 'uploads', label: 'File uploads' },
    ],
  },
  {
    id: 'customRequirements',
    label: 'Anything else?',
    description: 'Add constraints, must-have routes, integrations, or product details.',
    type: 'textarea',
    category: 'foundation',
    placeholder: 'Example: Preserve /contacts, /companies, /tasks, and /pipeline exactly.',
  },
];
