import {
  CAPABILITY_REGISTRY_VERSION,
  type CapabilityDefinition,
  type CapabilityProviderChoice,
} from './types';

function provider(
  id: string,
  label: string,
  category: CapabilityProviderChoice['category'],
  costBand: CapabilityProviderChoice['costBand'],
  hasFreeTier: boolean,
  assumptions: string[] = []
): CapabilityProviderChoice {
  return { id, label, category, costBand, hasFreeTier, assumptions };
}

function definition(
  partial: Omit<
    CapabilityDefinition,
    | 'dependencyCapabilityIds'
    | 'conflictingCapabilityIds'
    | 'providerChoices'
    | 'requiredEnvironmentVariableNames'
    | 'recommendedPackages'
    | 'expectedArchitecturalArtifacts'
    | 'expectedRoutes'
    | 'expectedApis'
    | 'expectedDataModels'
    | 'expectedStorageRequirements'
    | 'acceptanceCriteriaTemplates'
    | 'validationStrategies'
    | 'budgetCompatibility'
    | 'supportedDeploymentAssumptions'
    | 'sourceMetadataVersion'
  > &
    Partial<CapabilityDefinition>
): CapabilityDefinition {
  return {
    dependencyCapabilityIds: [],
    conflictingCapabilityIds: [],
    providerChoices: [],
    requiredEnvironmentVariableNames: [],
    recommendedPackages: [],
    expectedArchitecturalArtifacts: [],
    expectedRoutes: [],
    expectedApis: [],
    expectedDataModels: [],
    expectedStorageRequirements: [],
    acceptanceCriteriaTemplates: [],
    validationStrategies: [],
    budgetCompatibility: ['free-first', 'lean', 'professional', 'growth'],
    supportedDeploymentAssumptions: ['Next.js web app'],
    sourceMetadataVersion: CAPABILITY_REGISTRY_VERSION,
    ...partial,
  };
}

export const capabilityDefinitions: CapabilityDefinition[] = [
  definition({
    id: 'framework-nextjs',
    category: 'foundation',
    displayName: 'Next.js App Router',
    description: 'Use Next.js as the application framework.',
    technicalDescription: 'Generate a Next.js App Router project with src/app routes.',
    applicability: 'required',
    recommendedPackages: ['next', 'react', 'react-dom'],
    expectedArchitecturalArtifacts: ['src/app/layout.tsx', 'src/app/page.tsx'],
    validationStrategies: ['file-exists', 'build'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'typescript',
    category: 'foundation',
    displayName: 'TypeScript',
    description: 'Use typed application code.',
    technicalDescription: 'Keep source strict-friendly and validate with tsc.',
    applicability: 'required',
    dependencyCapabilityIds: ['framework-nextjs'],
    recommendedPackages: ['typescript', '@types/react', '@types/node'],
    validationStrategies: ['type-check'],
    estimatedComplexity: 'low',
  }),
  definition({
    id: 'responsive-ui',
    category: 'frontend',
    displayName: 'Responsive UI',
    description: 'Support desktop and mobile layouts.',
    technicalDescription: 'Use responsive Tailwind layouts and avoid clipped content.',
    applicability: 'required',
    dependencyCapabilityIds: ['framework-nextjs'],
    expectedArchitecturalArtifacts: ['responsive layout classes'],
    validationStrategies: ['generated-quality'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'authentication',
    category: 'authentication',
    displayName: 'Authentication',
    description: 'Allow users to sign in and own data.',
    technicalDescription: 'Add a guarded user identity layer and auth-aware state.',
    applicability: 'optional',
    providerChoices: [
      provider('supabase-auth', 'Supabase Auth', 'authentication', 'low', true),
      provider('clerk-auth', 'Clerk', 'authentication', 'low', true),
    ],
    validationStrategies: ['manual-review', 'runtime-smoke'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'role-based-access',
    category: 'authorization',
    displayName: 'Role-Based Access',
    description: 'Use roles or permissions for different user types.',
    technicalDescription: 'Represent user roles and conditionally expose workflows.',
    applicability: 'optional',
    dependencyCapabilityIds: ['authentication'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'database',
    category: 'data',
    displayName: 'Database',
    description: 'Persist structured application records.',
    technicalDescription: 'Provide typed storage helpers for approved data models.',
    applicability: 'optional',
    expectedArchitecturalArtifacts: ['src/lib/*storage*', 'src/types/*'],
    validationStrategies: ['content-check', 'type-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'supabase-database',
    category: 'data',
    displayName: 'Supabase Database',
    description: 'Use Supabase for managed Postgres persistence.',
    technicalDescription: 'Use Supabase public config safely and keep secrets server-only.',
    applicability: 'optional',
    dependencyCapabilityIds: ['database'],
    providerChoices: [provider('supabase', 'Supabase Postgres', 'database', 'low', true)],
    requiredEnvironmentVariableNames: [
      'NEXT_PUBLIC_SUPABASE_URL',
      'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    ],
    supportedDeploymentAssumptions: ['Vercel', 'managed Postgres'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'file-storage',
    category: 'storage',
    displayName: 'File Storage',
    description: 'Store uploaded files and generated media.',
    technicalDescription: 'Provide a storage abstraction for file metadata and object storage.',
    applicability: 'optional',
    dependencyCapabilityIds: ['database'],
    expectedDataModels: ['Asset'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'image-upload',
    category: 'storage',
    displayName: 'Image Upload',
    description: 'Let users upload images or photos.',
    technicalDescription: 'Add image upload UI, validation, metadata, and storage handling.',
    applicability: 'optional',
    dependencyCapabilityIds: ['file-storage'],
    expectedArchitecturalArtifacts: ['upload input', 'image preview'],
    validationStrategies: ['runtime-smoke', 'manual-review'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'text-ai-generation',
    category: 'AI',
    displayName: 'Text AI Generation',
    description: 'Generate or transform text with AI.',
    technicalDescription: 'Route AI text requests through a guarded server/API layer.',
    applicability: 'optional',
    requiredEnvironmentVariableNames: ['OPENAI_API_KEY'],
    expectedApis: ['/api/ai/*'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'image-ai-generation',
    category: 'AI',
    displayName: 'Image AI Generation',
    description: 'Generate illustrations or image assets with AI.',
    technicalDescription: 'Generate images through a server-side AI provider and persist outputs when needed.',
    applicability: 'optional',
    dependencyCapabilityIds: ['text-ai-generation', 'file-storage'],
    requiredEnvironmentVariableNames: ['OPENAI_API_KEY'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'billing',
    category: 'billing',
    displayName: 'Billing',
    description: 'Accept payments or manage paid plans.',
    technicalDescription: 'Model billing state and keep payment provider secrets server-side.',
    applicability: 'optional',
    providerChoices: [provider('stripe', 'Stripe', 'billing', 'low', true)],
    requiredEnvironmentVariableNames: ['STRIPE_SECRET_KEY'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'subscriptions',
    category: 'billing',
    displayName: 'Subscriptions',
    description: 'Support recurring paid plans.',
    technicalDescription: 'Represent subscription plans, entitlement state, and billing lifecycle.',
    applicability: 'optional',
    dependencyCapabilityIds: ['billing'],
    expectedDataModels: ['Subscription', 'Plan'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'transactional-email',
    category: 'communication',
    displayName: 'Transactional Email',
    description: 'Send account, receipt, or workflow emails.',
    technicalDescription: 'Use a server-side email provider wrapper and templates.',
    applicability: 'optional',
    providerChoices: [provider('resend', 'Resend', 'email', 'low', true)],
    requiredEnvironmentVariableNames: ['RESEND_API_KEY'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'notifications',
    category: 'communication',
    displayName: 'Notifications',
    description: 'Notify users about important workflow events.',
    technicalDescription: 'Represent notification state and delivery channels.',
    applicability: 'optional',
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'analytics',
    category: 'analytics',
    displayName: 'Analytics',
    description: 'Track product or business metrics.',
    technicalDescription: 'Add analytics events, dashboards, or reporting views.',
    applicability: 'optional',
    expectedRoutes: ['/analytics', '/dashboard'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'monitoring',
    category: 'operations',
    displayName: 'Monitoring',
    description: 'Track errors and operational health.',
    technicalDescription: 'Prepare instrumentation and error reporting boundaries.',
    applicability: 'optional',
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'background-jobs',
    category: 'operations',
    displayName: 'Background Jobs',
    description: 'Run asynchronous work outside immediate UI actions.',
    technicalDescription: 'Represent queued or deferred workflows with safe execution assumptions.',
    applicability: 'optional',
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'scheduled-jobs',
    category: 'operations',
    displayName: 'Scheduled Jobs',
    description: 'Run recurring or time-based tasks.',
    technicalDescription: 'Use cron-compatible scheduled workflows.',
    applicability: 'optional',
    dependencyCapabilityIds: ['background-jobs'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'search',
    category: 'frontend',
    displayName: 'Search',
    description: 'Let users find records quickly.',
    technicalDescription: 'Add searchable lists, filters, and query state.',
    applicability: 'optional',
    validationStrategies: ['runtime-smoke', 'content-check'],
    estimatedComplexity: 'low',
  }),
  definition({
    id: 'admin-dashboard',
    category: 'frontend',
    displayName: 'Admin Dashboard',
    description: 'Provide an admin or operations overview.',
    technicalDescription: 'Create role-aware dashboard routes and overview widgets.',
    applicability: 'optional',
    dependencyCapabilityIds: ['authentication', 'role-based-access'],
    expectedRoutes: ['/dashboard', '/admin'],
    validationStrategies: ['route-exists', 'generated-quality'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'crud',
    category: 'data',
    displayName: 'CRUD Workflows',
    description: 'Create, edit, delete, and browse records.',
    technicalDescription: 'Implement record lifecycle operations with typed state and persistence.',
    applicability: 'optional',
    dependencyCapabilityIds: ['database'],
    validationStrategies: ['runtime-smoke', 'content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'rich-editor',
    category: 'frontend',
    displayName: 'Rich Editor',
    description: 'Edit rich text or structured content.',
    technicalDescription: 'Provide editor controls and persistence for rich content blocks.',
    applicability: 'optional',
    dependencyCapabilityIds: ['crud'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'page-editor',
    category: 'frontend',
    displayName: 'Page Editor',
    description: 'Edit page-by-page or section-based content.',
    technicalDescription: 'Represent pages as editable ordered records with preview state.',
    applicability: 'optional',
    dependencyCapabilityIds: ['crud'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'high',
  }),
  definition({
    id: 'media-library',
    category: 'storage',
    displayName: 'Media Library',
    description: 'Browse and reuse uploaded or generated media.',
    technicalDescription: 'Provide asset records, thumbnail views, and selection workflows.',
    applicability: 'optional',
    dependencyCapabilityIds: ['file-storage'],
    expectedDataModels: ['MediaAsset'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'deployment-vercel',
    category: 'deployment',
    displayName: 'Vercel Deployment',
    description: 'Prepare the app for Vercel deployment.',
    technicalDescription: 'Assume a Vercel-compatible Next.js deployment target.',
    applicability: 'optional',
    dependencyCapabilityIds: ['framework-nextjs'],
    providerChoices: [provider('vercel', 'Vercel', 'deployment', 'low', true)],
    supportedDeploymentAssumptions: ['Vercel'],
    validationStrategies: ['build'],
    estimatedComplexity: 'low',
  }),
  definition({
    id: 'child-profile-management',
    category: 'domain-specific',
    displayName: 'Child Profiles',
    description: 'Manage child-safe profile information.',
    technicalDescription: 'Represent child profile records without exposing sensitive data.',
    applicability: 'optional',
    dependencyCapabilityIds: ['authentication', 'database'],
    expectedDataModels: ['ChildProfile'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'character-profile-management',
    category: 'domain-specific',
    displayName: 'Character Profiles',
    description: 'Save reusable story characters.',
    technicalDescription: 'Model reusable character profiles for story generation.',
    applicability: 'optional',
    dependencyCapabilityIds: ['database', 'crud'],
    expectedDataModels: ['CharacterProfile'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'story-crud',
    category: 'domain-specific',
    displayName: 'Story Management',
    description: 'Create, edit, save, and delete stories.',
    technicalDescription: 'Model story records, page records, and editing workflows.',
    applicability: 'optional',
    dependencyCapabilityIds: ['crud'],
    expectedDataModels: ['Story'],
    validationStrategies: ['content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'story-library',
    category: 'domain-specific',
    displayName: 'Story Library',
    description: 'Browse saved stories and drafts.',
    technicalDescription: 'Provide a library route or section for saved story records.',
    applicability: 'optional',
    dependencyCapabilityIds: ['story-crud', 'search'],
    expectedRoutes: ['/library', '/stories'],
    validationStrategies: ['route-exists', 'content-check'],
    estimatedComplexity: 'medium',
  }),
  definition({
    id: 'parental-safety-review',
    category: 'domain-specific',
    displayName: 'Parental Safety Review',
    description: 'Support review controls for children-focused content.',
    technicalDescription: 'Represent content review checkpoints and parent-visible controls.',
    applicability: 'optional',
    dependencyCapabilityIds: ['authentication'],
    validationStrategies: ['manual-review'],
    estimatedComplexity: 'medium',
  }),
];

export const capabilityRegistry = new Map(
  capabilityDefinitions.map((definition) => [definition.id, definition])
);

export function getCapabilityDefinition(
  capabilityId: string
): CapabilityDefinition | undefined {
  return capabilityRegistry.get(capabilityId);
}

export function getCapabilityDefinitions(): CapabilityDefinition[] {
  return [...capabilityDefinitions];
}
