import type { FileLanguage, FileNode } from '@/app/chat-workspace/components/types';

export const NEXT_SCAFFOLD_PATHS = [
  'package.json',
  'tsconfig.json',
  'next.config.mjs',
  'postcss.config.js',
  'tailwind.config.ts',
  'src/app/globals.css',
  'src/app/layout.tsx',
] as const;

export type NextScaffoldPath = (typeof NEXT_SCAFFOLD_PATHS)[number];

const SAFE_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

html,
body {
  min-height: 100%;
}

body {
  margin: 0;
  background: #f9fafb;
  color: #111827;
}

::-webkit-scrollbar {
  width: 8px;
  background: transparent;
}

::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 9999px;
}
`;

export const NEXT_SCAFFOLD_TEMPLATES: Record<NextScaffoldPath, { language: FileLanguage; content: string }> = {
  'package.json': {
    language: 'json',
    content: `${JSON.stringify(
      {
        name: 'matrix-coder-generated-app',
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          'type-check': 'tsc --noEmit',
          lint: 'next lint',
        },
        dependencies: {
          next: '15.1.11',
          react: '19.0.3',
          'react-dom': '19.0.3',
        },
        devDependencies: {
          '@types/node': '^20.0.0',
          '@types/react': '19.0.3',
          '@types/react-dom': '19.0.3',
          autoprefixer: '^10.4.0',
          postcss: '^8.4.0',
          tailwindcss: '3.4.6',
          typescript: '^5.0.0',
        },
      },
      null,
      2
    )}\n`,
  },
  'tsconfig.json': {
    language: 'json',
    content: `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          baseUrl: '.',
          paths: {
            '@/*': ['./src/*'],
          },
          plugins: [
            {
              name: 'next',
            },
          ],
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2
    )}\n`,
  },
  'next.config.mjs': {
    language: 'javascript',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`,
  },
  'postcss.config.js': {
    language: 'javascript',
    content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
  },
  'tailwind.config.ts': {
    language: 'typescript',
    content: `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,
  },
  'src/app/globals.css': {
    language: 'css',
    content: SAFE_GLOBALS_CSS,
  },
  'src/app/layout.tsx': {
    language: 'typescript',
    content: `import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Generated App',
  description: 'Generated by Matrix Coder AI',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  },
};

export function createNextScaffoldFiles(now = new Date().toISOString()): FileNode[] {
  return NEXT_SCAFFOLD_PATHS.map((path) => {
    const template = NEXT_SCAFFOLD_TEMPLATES[path];
    return {
      id: `scaffold-${path}`,
      name: path.split('/').pop() ?? path,
      path,
      type: 'file',
      language: template.language,
      content: template.content,
      size: template.content.length,
      lastModified: now,
      isNew: true,
    };
  });
}
