import type { BuildSuiteItem } from './types';

export const animationItems: BuildSuiteItem[] = [
  {
    id: 'minimal-motion',
    label: 'Minimal Motion',
    category: 'Subtle',
    description: 'Small hover, focus, and transition polish only.',
    tags: ['subtle', 'hover', 'transitions'],
    promptInstruction:
      'Use minimal motion with subtle hover states, focus transitions, and no distracting page-level animation.',
    complexity: 'low',
  },
  {
    id: 'dashboard-motion',
    label: 'Dashboard Motion',
    category: 'Product',
    description: 'Polished card, chart, and status transitions.',
    tags: ['dashboard', 'cards', 'status'],
    promptInstruction:
      'Use restrained dashboard motion for cards, status chips, tabs, and progress elements while respecting reduced-motion preferences.',
    complexity: 'medium',
  },
  {
    id: 'expressive-motion',
    label: 'Expressive Motion',
    category: 'Rich',
    description: 'More energetic transitions for playful or consumer apps.',
    tags: ['expressive', 'playful', 'consumer'],
    promptInstruction:
      'Use expressive but tasteful motion for key interactions, selected states, and onboarding-style moments without hurting usability.',
    complexity: 'medium',
  },
  {
    id: 'animated-gradients',
    label: 'Animated Gradients',
    category: 'Rich',
    description: 'Subtle gradient movement for premium hero and status surfaces.',
    tags: ['gradient', 'animated', 'premium'],
    promptInstruction:
      'Use subtle animated gradients only in contained hero or status surfaces, with reduced-motion-friendly fallbacks and no distracting background blobs.',
    complexity: 'medium',
  },
  {
    id: 'framer-motion-style',
    label: 'Framer Motion',
    category: 'Rich',
    description: 'Framer-inspired transitions without adding animation dependencies.',
    tags: ['framer', 'motion', 'transitions'],
    promptInstruction:
      'Use Framer Motion-inspired interaction patterns with smooth enter, hover, and selected-state transitions using CSS only unless dependencies are explicitly allowed.',
    complexity: 'medium',
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'animation-motion',
    badges: ['Popular', 'Advanced'],
    recommendedFor: ['Best for AI Apps', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'portfolio', 'fitness-tracker'] },
  },
  {
    id: 'scroll-reveal',
    label: 'Scroll Reveal',
    category: 'Rich',
    description: 'Subtle section reveals for landing and content-heavy pages.',
    tags: ['scroll', 'reveal', 'sections'],
    promptInstruction:
      'Use subtle scroll-reveal style section polish with CSS transitions and reduced-motion-friendly fallbacks.',
    complexity: 'medium',
    icon: 'zap',
    accentColor: 'cyan',
    previewType: 'animation-motion',
    badges: ['Premium'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['portfolio', 'saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'page-transitions',
    label: 'Page Transitions',
    category: 'Product',
    description: 'Route and view transition polish for multi-page apps.',
    tags: ['page', 'routes', 'transitions'],
    promptInstruction:
      'Use restrained page and view transition polish between major screens, keeping navigation fast and not blocking route changes.',
    complexity: 'medium',
    icon: 'zap',
    accentColor: 'blue',
    previewType: 'animation-motion',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'expense-tracker', 'saas-dashboard'] },
  },
  {
    id: 'floating-motion',
    label: 'Floating',
    category: 'Subtle',
    description: 'Gentle floating effects for hero cards and status surfaces.',
    tags: ['floating', 'cards', 'subtle'],
    promptInstruction:
      'Use gentle floating motion for small hero or status surfaces only, avoiding distracting decorative blobs and preserving reduced-motion behavior.',
    complexity: 'low',
    icon: 'sparkles',
    accentColor: 'emerald',
    previewType: 'animation-motion',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['fitness-tracker', 'portfolio', 'habit-tracker'] },
  },
  {
    id: 'morphing-motion',
    label: 'Morphing',
    category: 'Rich',
    description: 'Shape and state changes for expressive app moments.',
    tags: ['morphing', 'shape', 'state'],
    promptInstruction:
      'Use tasteful morphing-inspired state changes for selected controls or visual summaries, keeping layout dimensions stable.',
    complexity: 'high',
    icon: 'zap',
    accentColor: 'violet',
    previewType: 'animation-motion',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['habit-tracker', 'fitness-tracker', 'saas-dashboard'] },
  },
  {
    id: 'ripple-effects',
    label: 'Ripple',
    category: 'Product',
    description: 'Material-inspired action feedback for buttons and controls.',
    tags: ['ripple', 'buttons', 'feedback'],
    promptInstruction:
      'Use ripple-inspired action feedback for buttons and interactive controls with accessible focus and hover states.',
    complexity: 'medium',
    icon: 'zap',
    accentColor: 'blue',
    previewType: 'animation-motion',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['booking-scheduler', 'expense-tracker', 'ecommerce-admin'] },
  },
  {
    id: 'confetti',
    label: 'Confetti',
    category: 'Feedback',
    description: 'Celebration feedback for completed goals and milestones.',
    tags: ['confetti', 'celebration', 'milestones'],
    promptInstruction:
      'Include lightweight confetti-inspired celebration feedback for meaningful completed actions or milestones without adding external animation libraries.',
    complexity: 'medium',
    icon: 'sparkles',
    accentColor: 'amber',
    previewType: 'animation-motion',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['habit-tracker', 'fitness-tracker', 'kanban-board'] },
  },
  {
    id: 'cursor-effects',
    label: 'Cursor Effects',
    category: 'Expressive',
    description: 'Pointer-aware polish for premium desktop experiences.',
    tags: ['cursor', 'pointer', 'desktop'],
    promptInstruction:
      'Use subtle cursor-aware effects only for desktop-enhanced moments, ensuring the app still works normally on touch devices.',
    complexity: 'high',
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'animation-motion',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['portfolio', 'saas-dashboard'] },
  },
  {
    id: 'loading-skeletons',
    label: 'Loading Skeletons',
    category: 'Product',
    description: 'Loading-safe skeleton states for panels, tables, and cards.',
    tags: ['loading', 'skeleton', 'states'],
    promptInstruction:
      'Include loading skeleton states for key panels, tables, cards, or route content so the app feels production-ready during async-like states.',
    complexity: 'medium',
    icon: 'blocks',
    accentColor: 'slate',
    previewType: 'component-cards',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'saas-dashboard', 'inventory-manager'] },
  },
  {
    id: 'shimmer',
    label: 'Shimmer',
    category: 'Product',
    description: 'Subtle shimmer effects for loading and highlighted surfaces.',
    tags: ['shimmer', 'loading', 'highlight'],
    promptInstruction:
      'Use restrained shimmer effects for loading placeholders or highlighted surfaces, with reduced-motion-friendly fallbacks.',
    complexity: 'medium',
    icon: 'sparkles',
    accentColor: 'cyan',
    previewType: 'animation-motion',
    badges: ['Premium'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'ecommerce-admin', 'portfolio'] },
  },
  {
    id: 'lottie-support',
    label: 'Lottie Support',
    category: 'Rich',
    description: 'Lottie-ready placement and empty states without installing packages.',
    tags: ['lottie', 'animation', 'empty-states'],
    promptInstruction:
      'Include Lottie-ready placeholder areas for future animation assets, but do not install Lottie packages or require external files.',
    complexity: 'medium',
    icon: 'sparkles',
    accentColor: 'violet',
    previewType: 'animation-motion',
    badges: ['Premium'],
    recommendedFor: ['Best for Mobile', 'Best for AI Apps'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['booking-scheduler', 'habit-tracker', 'portfolio'] },
  },
];
