import type { BuildSuiteItem } from './types';

export const componentItems: BuildSuiteItem[] = [
  {
    id: 'data-tables',
    label: 'Data Tables',
    category: 'Data',
    description: 'Sortable table-style lists with filters, empty states, and actions.',
    tags: ['tables', 'filters', 'empty-states'],
    promptInstruction:
      'Include polished data tables or table-like lists with filters, empty states, inline actions, and clear row metadata.',
    complexity: 'medium',
  },
  {
    id: 'charts-metrics',
    label: 'Charts and Metrics',
    category: 'Analytics',
    description: 'Metric cards, trend summaries, and lightweight chart sections.',
    tags: ['charts', 'metrics', 'analytics'],
    promptInstruction:
      'Include metric cards, trend summaries, and lightweight chart or progress visualizations that match the selected app domain.',
    complexity: 'medium',
  },
  {
    id: 'forms-crud',
    label: 'Forms and CRUD',
    category: 'Workflow',
    description: 'Add, edit, delete, search, and filter workflows.',
    tags: ['forms', 'crud', 'search', 'filters'],
    promptInstruction:
      'Include complete add, edit, delete, search, and filter workflows with validation-friendly local state and clear form labels.',
    complexity: 'high',
  },
  {
    id: 'calendar-schedule',
    label: 'Calendar Schedule',
    category: 'Scheduling',
    description: 'Calendar-like date selectors, appointments, and schedule cards.',
    tags: ['calendar', 'schedule', 'appointments'],
    promptInstruction:
      'Include calendar or schedule-oriented components with date selection, upcoming items, and status-aware schedule cards.',
    complexity: 'high',
  },
  {
    id: 'kanban-board',
    label: 'Kanban Board',
    category: 'Workflow',
    description: 'Column-based boards for moving items between stages.',
    tags: ['kanban', 'stages', 'drag-ready'],
    promptInstruction:
      'Include a kanban-style board with domain-specific stages, movable cards, status counts, and clear empty columns.',
    complexity: 'high',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    category: 'Feedback',
    description: 'Status messages, alerts, reminders, and activity feedback.',
    tags: ['notifications', 'alerts', 'activity'],
    promptInstruction:
      'Include polished notification and activity feedback patterns with status-aware messages, reminders, and readable empty states.',
    complexity: 'medium',
  },
  {
    id: 'floating-cards',
    label: 'Floating Cards',
    category: 'Surface',
    description: 'Layered elevated cards that make complex screens easier to scan.',
    tags: ['cards', 'floating', 'surface'],
    promptInstruction:
      'Use floating cards for key content groups, with stable spacing, clear elevation, and responsive wrapping.',
    complexity: 'low',
  },
  {
    id: 'blur-navigation',
    label: 'Blur Navigation',
    category: 'Navigation',
    description: 'Translucent navigation bars with readable blur-backed surfaces.',
    tags: ['navigation', 'blur', 'glass'],
    promptInstruction:
      'Use blur-backed navigation surfaces where appropriate, keeping text readable and avoiding overlap with page content.',
    complexity: 'medium',
  },
  {
    id: 'soft-shadows',
    label: 'Soft Shadows',
    category: 'Surface',
    description: 'Subtle elevation that keeps cards polished without visual noise.',
    tags: ['shadows', 'surface', 'depth'],
    promptInstruction:
      'Use soft, restrained shadows to separate cards and panels while preserving a clean professional interface.',
    complexity: 'low',
  },
  {
    id: 'search-filters',
    label: 'Search and Filters',
    category: 'Data',
    description: 'Fast search fields, filters, segmented controls, and result counts.',
    tags: ['search', 'filters', 'data'],
    promptInstruction:
      'Include search and filter controls with result counts, clear reset states, and domain-specific filter options.',
    complexity: 'medium',
  },
  {
    id: 'accordions',
    label: 'Accordions',
    category: 'Content',
    description: 'Expandable content groups for settings, FAQs, and dense details.',
    tags: ['accordion', 'disclosure', 'content'],
    promptInstruction:
      'Include accessible accordion sections for dense details, settings, or FAQ-like content with clear expanded and collapsed states.',
    complexity: 'low',
    icon: 'component',
    accentColor: 'emerald',
    previewType: 'component-cards',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['saas-dashboard', 'knowledge-base', 'personal-crm'] },
  },
  {
    id: 'tabs',
    label: 'Tabs',
    category: 'Navigation',
    description: 'Segmented tab views for switching between related screens or states.',
    tags: ['tabs', 'navigation', 'views'],
    promptInstruction:
      'Include polished tabbed views for related data groups, preserving clear selected states and responsive wrapping.',
    complexity: 'low',
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-top-nav',
    badges: ['Popular', 'Easy'],
    recommendedFor: ['Recommended for Beginners', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['personal-crm', 'expense-tracker', 'saas-dashboard'] },
  },
  {
    id: 'drawers',
    label: 'Drawers',
    category: 'Overlay',
    description: 'Slide-out panels for details, filters, and secondary workflows.',
    tags: ['drawer', 'panel', 'overlay'],
    promptInstruction:
      'Include slide-out drawer patterns for details or filters, with clear close actions and mobile-friendly sizing.',
    complexity: 'medium',
    icon: 'component',
    accentColor: 'violet',
    previewType: 'layout-sidebar',
    badges: ['Advanced'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'inventory-manager', 'ecommerce-admin'] },
  },
  {
    id: 'sidebars',
    label: 'Sidebars',
    category: 'Navigation',
    description: 'Persistent navigation and context panels for workspace apps.',
    tags: ['sidebar', 'navigation', 'workspace'],
    promptInstruction:
      'Include sidebar navigation or context panels for workspace-style apps, with route links and active states.',
    complexity: 'medium',
    icon: 'layout-dashboard',
    accentColor: 'blue',
    previewType: 'layout-sidebar',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'saas-dashboard', 'inventory-manager'] },
  },
  {
    id: 'modals',
    label: 'Modals',
    category: 'Overlay',
    description: 'Focused dialogs for confirmations, editing, and quick actions.',
    tags: ['modal', 'dialog', 'confirmation'],
    promptInstruction:
      'Include modal dialogs for confirmation, quick editing, or focused actions, with clear keyboard-safe close and cancel states.',
    complexity: 'medium',
    icon: 'component',
    accentColor: 'fuchsia',
    previewType: 'component-cards',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'expense-tracker', 'ecommerce-admin'] },
  },
  {
    id: 'toasts',
    label: 'Toasts',
    category: 'Feedback',
    description: 'Lightweight success, warning, and error messages.',
    tags: ['toast', 'feedback', 'status'],
    promptInstruction:
      'Include toast-style feedback for save, delete, and status actions, using clear success, warning, and error variants.',
    complexity: 'medium',
    icon: 'star',
    accentColor: 'amber',
    previewType: 'component-notifications',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['expense-tracker', 'personal-crm', 'habit-tracker'] },
  },
  {
    id: 'carousels',
    label: 'Carousels',
    category: 'Content',
    description: 'Horizontal content browsing for cards, testimonials, or products.',
    tags: ['carousel', 'cards', 'content'],
    promptInstruction:
      'Include a lightweight carousel or horizontal card rail where it naturally fits, with stable sizing and accessible controls.',
    complexity: 'medium',
    icon: 'blocks',
    accentColor: 'violet',
    previewType: 'component-cards',
    badges: ['Premium'],
    recommendedFor: ['Best for Mobile'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['ecommerce-admin', 'portfolio', 'booking-scheduler'] },
  },
  {
    id: 'timelines',
    label: 'Timelines',
    category: 'Content',
    description: 'Chronological activity, history, and milestone displays.',
    tags: ['timeline', 'activity', 'history'],
    promptInstruction:
      'Include a timeline for activity, milestones, follow-ups, or events when the domain benefits from chronological context.',
    complexity: 'medium',
    icon: 'calendar',
    accentColor: 'cyan',
    previewType: 'component-notifications',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'booking-scheduler', 'habit-tracker'] },
  },
  {
    id: 'ratings',
    label: 'Ratings',
    category: 'Feedback',
    description: 'Stars, scores, reviews, and quality indicators.',
    tags: ['ratings', 'reviews', 'stars'],
    promptInstruction:
      'Include rating or scoring UI where useful, with clear labels, selected states, and summary counts.',
    complexity: 'low',
    icon: 'star',
    accentColor: 'amber',
    previewType: 'component-cards',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['ecommerce-admin', 'booking-scheduler', 'portfolio'] },
  },
  {
    id: 'pricing-tables',
    label: 'Pricing Tables',
    category: 'Commerce',
    description: 'Tiered plan cards for SaaS, memberships, and subscriptions.',
    tags: ['pricing', 'plans', 'subscriptions'],
    promptInstruction:
      'Include pricing table sections with clear plan comparison, highlighted recommendations, and honest disabled purchase states unless payments are explicitly requested.',
    complexity: 'medium',
    icon: 'table',
    accentColor: 'emerald',
    previewType: 'component-cards',
    badges: ['SaaS', 'Production Ready'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'testimonials',
    label: 'Testimonials',
    category: 'Marketing',
    description: 'Customer quotes, proof points, and trust-building cards.',
    tags: ['testimonials', 'social-proof', 'marketing'],
    promptInstruction:
      'Include testimonial or social-proof cards when building marketing-facing products, keeping them compact and credible.',
    complexity: 'low',
    icon: 'star',
    accentColor: 'blue',
    previewType: 'component-cards',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['portfolio', 'saas-dashboard', 'booking-scheduler'] },
  },
  {
    id: 'faq-sections',
    label: 'FAQ',
    category: 'Content',
    description: 'Question-and-answer sections for onboarding and support.',
    tags: ['faq', 'support', 'questions'],
    promptInstruction:
      'Include a concise FAQ section with practical domain-specific questions and scannable answers.',
    complexity: 'low',
    icon: 'component',
    accentColor: 'lime',
    previewType: 'component-cards',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['saas-dashboard', 'booking-scheduler', 'ecommerce-admin'] },
  },
  {
    id: 'hero-sections',
    label: 'Hero Sections',
    category: 'Marketing',
    description: 'Strong first screens with clear value and route entry points.',
    tags: ['hero', 'landing', 'cta'],
    promptInstruction:
      'Include a polished hero section that introduces the app and links directly into real primary app routes or workflows.',
    complexity: 'medium',
    icon: 'app-window',
    accentColor: 'fuchsia',
    previewType: 'layout-landing',
    badges: ['Popular'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'portfolio', 'ecommerce-admin'] },
  },
  {
    id: 'footers',
    label: 'Footers',
    category: 'Navigation',
    description: 'Utility navigation, status links, and support areas.',
    tags: ['footer', 'navigation', 'utility'],
    promptInstruction:
      'Include a footer only when useful, with concise utility links and product context that does not distract from the app.',
    complexity: 'low',
    icon: 'layout-dashboard',
    accentColor: 'slate',
    previewType: 'layout-landing',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['portfolio', 'saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'navigation-bars',
    label: 'Navigation Bars',
    category: 'Navigation',
    description: 'Primary top navigation with route links and active states.',
    tags: ['nav', 'navigation', 'routes'],
    promptInstruction:
      'Include a primary navigation bar with real route links, active states, and responsive behavior.',
    complexity: 'low',
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-top-nav',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['personal-crm', 'fitness-tracker', 'expense-tracker'] },
  },
  {
    id: 'mega-menus',
    label: 'Mega Menus',
    category: 'Navigation',
    description: 'Large organized navigation menus for complex products.',
    tags: ['mega-menu', 'navigation', 'taxonomy'],
    promptInstruction:
      'Include a mega-menu style navigation pattern only for apps with many sections, keeping groups readable and route links real.',
    complexity: 'high',
    icon: 'layout-dashboard',
    accentColor: 'violet',
    previewType: 'layout-top-nav',
    badges: ['Advanced', 'Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['ecommerce-admin', 'saas-dashboard', 'knowledge-base'] },
  },
  {
    id: 'search-bars',
    label: 'Search Bars',
    category: 'Data',
    description: 'Prominent searchable controls for lists, docs, and records.',
    tags: ['search', 'query', 'filters'],
    promptInstruction:
      'Include prominent search bars with helpful placeholders, result counts, and empty states for searchable content.',
    complexity: 'low',
    icon: 'search',
    accentColor: 'emerald',
    previewType: 'component-tables',
    badges: ['Popular', 'Easy'],
    recommendedFor: ['Recommended for Beginners', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['personal-crm', 'inventory-manager', 'knowledge-base'] },
  },
  {
    id: 'command-palettes',
    label: 'Command Palettes',
    category: 'Power User',
    description: 'Keyboard-first command surfaces for navigation and quick actions.',
    tags: ['command', 'keyboard', 'search'],
    promptInstruction:
      'Include a command-palette style quick action surface for advanced navigation and domain actions, without requiring external libraries.',
    complexity: 'high',
    icon: 'search',
    accentColor: 'fuchsia',
    previewType: 'ai-assistant',
    badges: ['Advanced', 'AI Ready'],
    recommendedFor: ['Best for AI Apps', 'Best for SaaS'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['saas-dashboard', 'personal-crm', 'ide-workspace'] },
  },
  {
    id: 'file-uploaders',
    label: 'File Uploaders',
    category: 'Files',
    description: 'Drag-ready upload areas and file state displays.',
    tags: ['upload', 'files', 'drag-drop'],
    promptInstruction:
      'Include client-safe file upload UI placeholders with selected-file states, validation messaging, and no backend upload calls unless explicitly requested.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'blue',
    previewType: 'component-forms',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['inventory-manager', 'ecommerce-admin', 'portfolio'] },
  },
  {
    id: 'rich-text-editors',
    label: 'Rich Text Editors',
    category: 'Content',
    description: 'Editor-style input areas for notes, docs, and long-form fields.',
    tags: ['editor', 'rich-text', 'content'],
    promptInstruction:
      'Include a rich-text-editor inspired composing surface with toolbar affordances, draft states, and plain React state only.',
    complexity: 'high',
    icon: 'form',
    accentColor: 'violet',
    previewType: 'component-forms',
    badges: ['Advanced'],
    recommendedFor: ['Best for SaaS', 'Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['knowledge-base', 'personal-crm', 'portfolio'] },
  },
  {
    id: 'calendars',
    label: 'Calendars',
    category: 'Scheduling',
    description: 'Month grids, date summaries, and event cards.',
    tags: ['calendar', 'dates', 'events'],
    promptInstruction:
      'Include calendar UI for date-based workflows, with selected dates, upcoming items, and clear empty states.',
    complexity: 'high',
    icon: 'calendar',
    accentColor: 'cyan',
    previewType: 'component-calendar',
    badges: ['Advanced'],
    recommendedFor: ['Best for Mobile', 'Production Ready'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['booking-scheduler', 'habit-tracker', 'personal-crm'] },
  },
  {
    id: 'chat-windows',
    label: 'Chat Windows',
    category: 'AI',
    description: 'Conversation panels for support, assistants, and collaboration.',
    tags: ['chat', 'messages', 'assistant'],
    promptInstruction:
      'Include a chat-window interface for assistant, support, or collaboration workflows, with message states and safe local mock data.',
    complexity: 'high',
    icon: 'brain-circuit',
    accentColor: 'fuchsia',
    previewType: 'ai-assistant',
    badges: ['AI Ready', 'Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['saas-dashboard', 'knowledge-base', 'personal-crm'] },
  },
  {
    id: 'line-charts',
    label: 'Line Charts',
    category: 'Charts',
    description: 'Trend lines for growth, habits, finances, and activity.',
    tags: ['charts', 'line', 'trends'],
    promptInstruction:
      'Include lightweight line-chart style visualizations for trends using CSS/SVG-safe markup without adding chart dependencies.',
    complexity: 'medium',
    icon: 'chart',
    accentColor: 'cyan',
    previewType: 'component-charts',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'expense-tracker', 'fitness-tracker'] },
  },
  {
    id: 'area-charts',
    label: 'Area Charts',
    category: 'Charts',
    description: 'Filled trend visuals for totals, volume, and progress.',
    tags: ['charts', 'area', 'trends'],
    promptInstruction:
      'Include area-chart style sections for cumulative or volume-based metrics using lightweight CSS/SVG patterns.',
    complexity: 'medium',
    icon: 'chart',
    accentColor: 'blue',
    previewType: 'component-charts',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'inventory-manager', 'expense-tracker'] },
  },
  {
    id: 'pie-charts',
    label: 'Pie Charts',
    category: 'Charts',
    description: 'Category breakdowns for spend, inventory, and progress.',
    tags: ['charts', 'pie', 'breakdown'],
    promptInstruction:
      'Include pie or donut chart style category breakdowns with labels, legends, and accessible summary text.',
    complexity: 'medium',
    icon: 'chart',
    accentColor: 'amber',
    previewType: 'component-charts',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['expense-tracker', 'inventory-manager', 'saas-dashboard'] },
  },
  {
    id: 'bar-charts',
    label: 'Bar Charts',
    category: 'Charts',
    description: 'Comparative bars for counts, revenue, progress, and inventory.',
    tags: ['charts', 'bar', 'comparison'],
    promptInstruction:
      'Include bar-chart style comparisons for key domain metrics with readable labels and responsive sizing.',
    complexity: 'medium',
    icon: 'chart',
    accentColor: 'emerald',
    previewType: 'component-charts',
    badges: ['Popular', 'Easy'],
    recommendedFor: ['Recommended for Beginners', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'fitness-tracker', 'ecommerce-admin'] },
  },
  {
    id: 'heatmaps',
    label: 'Heatmaps',
    category: 'Charts',
    description: 'Density grids for calendar, usage, and performance patterns.',
    tags: ['charts', 'heatmap', 'density'],
    promptInstruction:
      'Include heatmap-style grids for activity, usage, or intensity patterns with clear legends and hover-ready cells.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'lime',
    previewType: 'component-charts',
    badges: ['Advanced'],
    recommendedFor: ['Best for SaaS', 'Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['saas-dashboard', 'habit-tracker', 'analytics-dashboard'] },
  },
  {
    id: 'treemaps',
    label: 'Treemaps',
    category: 'Charts',
    description: 'Nested block visualizations for composition and allocation.',
    tags: ['charts', 'treemap', 'composition'],
    promptInstruction:
      'Include treemap-inspired block visualizations for portfolio, category, or inventory composition.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'violet',
    previewType: 'component-charts',
    badges: ['Advanced'],
    recommendedFor: ['Best for SaaS'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['inventory-manager', 'saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'sankey-charts',
    label: 'Sankey Charts',
    category: 'Charts',
    description: 'Flow diagrams for funnels, pipelines, and money movement.',
    tags: ['charts', 'sankey', 'flow'],
    promptInstruction:
      'Include Sankey-inspired flow visuals for funnels, pipeline stages, or money movement using simple SVG/CSS-safe shapes.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'fuchsia',
    previewType: 'component-charts',
    badges: ['Advanced', 'Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['personal-crm', 'expense-tracker', 'saas-dashboard'] },
  },
  {
    id: 'radar-charts',
    label: 'Radar Charts',
    category: 'Charts',
    description: 'Multi-axis score visuals for performance and comparisons.',
    tags: ['charts', 'radar', 'scores'],
    promptInstruction:
      'Include radar-chart inspired score visuals for multi-dimensional performance, skill, or category comparisons.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'cyan',
    previewType: 'component-charts',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['fitness-tracker', 'saas-dashboard', 'habit-tracker'] },
  },
  {
    id: 'timeline-charts',
    label: 'Timeline Charts',
    category: 'Charts',
    description: 'Time-based milestones, events, and progress visuals.',
    tags: ['charts', 'timeline', 'events'],
    promptInstruction:
      'Include timeline-chart visuals for milestones, scheduled work, follow-ups, or historical progress.',
    complexity: 'medium',
    icon: 'calendar',
    accentColor: 'blue',
    previewType: 'component-notifications',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'booking-scheduler', 'kanban-board'] },
  },
  {
    id: 'financial-charts',
    label: 'Financial Charts',
    category: 'Charts',
    description: 'Revenue, balance, cashflow, and portfolio visuals.',
    tags: ['charts', 'finance', 'revenue'],
    promptInstruction:
      'Include financial chart visuals for balances, revenue, spending, forecasts, or portfolio movement with clear positive and negative states.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'emerald',
    previewType: 'component-charts',
    badges: ['Fintech', 'Advanced'],
    recommendedFor: ['Production Ready', 'Best for SaaS'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['expense-tracker', 'saas-dashboard', 'ecommerce-admin'] },
  },
];
