import type { BuildSuiteItem } from './types';

export const integrationItems: BuildSuiteItem[] = [
  {
    id: 'local-storage',
    label: 'Local Storage',
    category: 'Persistence',
    description: 'Browser localStorage persistence for generated demo data.',
    tags: ['localStorage', 'persistence', 'offline'],
    promptInstruction:
      'Use browser localStorage for persistence in client components, with loading-safe defaults and no server-side browser API usage.',
    complexity: 'medium',
  },
  {
    id: 'csv-export',
    label: 'CSV Export',
    category: 'Files',
    description: 'Export table or list data into CSV-like downloadable content.',
    tags: ['csv', 'export', 'files'],
    promptInstruction:
      'Add a client-safe CSV export action for the main domain records, with clear disabled and empty states.',
    complexity: 'medium',
  },
  {
    id: 'mock-api-ready',
    label: 'Mock API Ready',
    category: 'API',
    description: 'Use structured data helpers that can later be swapped for an API.',
    tags: ['api-ready', 'mock-data', 'helpers'],
    promptInstruction:
      'Structure demo data and helper functions so they can later be swapped for API calls, while keeping this generation fully local.',
    complexity: 'medium',
  },
  {
    id: 'auth-shell',
    label: 'Auth Shell',
    category: 'Auth',
    description: 'Show signed-in shell states without implementing real auth.',
    tags: ['auth', 'shell', 'user-menu'],
    promptInstruction:
      'Include a signed-in app shell with user menu placeholders and protected-area styling, but do not implement real authentication.',
    complexity: 'low',
  },
  {
    id: 'stripe-ready',
    label: 'Stripe',
    category: 'Payments',
    description: 'Payment-ready UI and plan states without live Stripe calls.',
    tags: ['stripe', 'payments', 'subscriptions'],
    promptInstruction:
      'Include Stripe-ready pricing and billing UI placeholders, but do not call Stripe APIs or add payment logic unless explicitly requested.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'violet',
    previewType: 'integration-flow',
    badges: ['SaaS', 'Production Ready'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'clerk-ready',
    label: 'Clerk',
    category: 'Auth',
    description: 'Auth-ready screens and user menu placeholders for Clerk.',
    tags: ['clerk', 'auth', 'users'],
    promptInstruction:
      'Include Clerk-ready auth surfaces such as sign-in placeholders, user menus, and protected-area states without calling Clerk or adding SDK code.',
    complexity: 'medium',
    icon: 'badge-check',
    accentColor: 'blue',
    previewType: 'integration-flow',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'firebase-ready',
    label: 'Firebase',
    category: 'Backend',
    description: 'Firebase-ready data structure and connection placeholders.',
    tags: ['firebase', 'backend', 'realtime'],
    promptInstruction:
      'Structure the app so Firebase persistence could be added later, with clear local mock helpers and no live Firebase calls.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'amber',
    previewType: 'integration-flow',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['habit-tracker', 'booking-scheduler', 'kanban-board'] },
  },
  {
    id: 'supabase-ready',
    label: 'Supabase',
    category: 'Backend',
    description: 'Supabase-ready schema thinking and local data boundaries.',
    tags: ['supabase', 'database', 'auth'],
    promptInstruction:
      'Structure local data and helper boundaries so Supabase can be connected later, without adding Supabase client calls or environment requirements.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'emerald',
    previewType: 'integration-flow',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'inventory-manager', 'saas-dashboard'] },
  },
  {
    id: 'openai-ready',
    label: 'OpenAI',
    category: 'AI',
    description: 'OpenAI-ready assistant surfaces and prompt-safe UI states.',
    tags: ['openai', 'ai', 'assistant'],
    promptInstruction:
      'Include OpenAI-ready assistant UI surfaces and prompt/result states, but do not call OpenAI APIs or add secrets.',
    complexity: 'medium',
    icon: 'brain-circuit',
    accentColor: 'fuchsia',
    previewType: 'ai-assistant',
    badges: ['AI Ready', 'Popular'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'knowledge-base', 'personal-crm'] },
  },
  {
    id: 'anthropic-ready',
    label: 'Anthropic',
    category: 'AI',
    description: 'Claude-ready AI workflow placeholders and safety states.',
    tags: ['anthropic', 'claude', 'ai'],
    promptInstruction:
      'Include Anthropic-ready AI workflow placeholders and response states, but do not call external AI APIs or add secrets.',
    complexity: 'medium',
    icon: 'brain-circuit',
    accentColor: 'violet',
    previewType: 'ai-assistant',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['knowledge-base', 'saas-dashboard'] },
  },
  {
    id: 'gemini-ready',
    label: 'Gemini',
    category: 'AI',
    description: 'Gemini-ready multimodal or assistant interface planning.',
    tags: ['gemini', 'ai', 'assistant'],
    promptInstruction:
      'Include Gemini-ready assistant or multimodal UI placeholders, but do not call Google or Gemini APIs.',
    complexity: 'medium',
    icon: 'brain-circuit',
    accentColor: 'blue',
    previewType: 'ai-assistant',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['knowledge-base', 'portfolio', 'saas-dashboard'] },
  },
  {
    id: 'resend-ready',
    label: 'Resend',
    category: 'Email',
    description: 'Email-ready transactional messaging states.',
    tags: ['resend', 'email', 'notifications'],
    promptInstruction:
      'Include Resend-ready email notification states and templates in the UI, but do not send email or add API calls.',
    complexity: 'low',
    icon: 'plug-zap',
    accentColor: 'cyan',
    previewType: 'integration-flow',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['booking-scheduler', 'personal-crm', 'ecommerce-admin'] },
  },
  {
    id: 'uploadthing-ready',
    label: 'UploadThing',
    category: 'Files',
    description: 'Upload-ready file controls and file management states.',
    tags: ['uploadthing', 'uploads', 'files'],
    promptInstruction:
      'Include UploadThing-ready upload UI and file list states, but do not install UploadThing or call upload APIs.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'blue',
    previewType: 'component-forms',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['portfolio', 'inventory-manager', 'ecommerce-admin'] },
  },
  {
    id: 'cloudinary-ready',
    label: 'Cloudinary',
    category: 'Media',
    description: 'Media-ready gallery and asset management placeholders.',
    tags: ['cloudinary', 'media', 'images'],
    promptInstruction:
      'Include Cloudinary-ready media gallery and asset management UI placeholders, but do not call Cloudinary or add SDK code.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'cyan',
    previewType: 'component-cards',
    badges: ['Premium'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['ecommerce-admin', 'portfolio'] },
  },
  {
    id: 'algolia-ready',
    label: 'Algolia',
    category: 'Search',
    description: 'Search-ready UX for fast indexed results.',
    tags: ['algolia', 'search', 'index'],
    promptInstruction:
      'Include Algolia-ready search UX patterns with facets, instant-result states, and empty states, but do not call Algolia APIs.',
    complexity: 'medium',
    icon: 'search',
    accentColor: 'blue',
    previewType: 'component-tables',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['ecommerce-admin', 'knowledge-base', 'inventory-manager'] },
  },
  {
    id: 'meilisearch-ready',
    label: 'Meilisearch',
    category: 'Search',
    description: 'Open-source search-ready facets and result lists.',
    tags: ['meilisearch', 'search', 'filters'],
    promptInstruction:
      'Include Meilisearch-ready search UI with fast filters, query states, and clear result ranking affordances, but no live search calls.',
    complexity: 'medium',
    icon: 'search',
    accentColor: 'emerald',
    previewType: 'component-tables',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['knowledge-base', 'inventory-manager', 'personal-crm'] },
  },
  {
    id: 'google-maps-ready',
    label: 'Google Maps',
    category: 'Maps',
    description: 'Map-ready location panels and address workflows.',
    tags: ['maps', 'locations', 'google'],
    promptInstruction:
      'Include Google Maps-ready location cards, address fields, and map placeholder panels, but do not load Google Maps scripts or APIs.',
    complexity: 'medium',
    icon: 'app-window',
    accentColor: 'lime',
    previewType: 'component-cards',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['booking-scheduler', 'inventory-manager', 'personal-crm'] },
  },
  {
    id: 'twilio-ready',
    label: 'Twilio',
    category: 'Messaging',
    description: 'SMS and communication-ready status surfaces.',
    tags: ['twilio', 'sms', 'messaging'],
    promptInstruction:
      'Include Twilio-ready SMS or communication status surfaces, contact consent fields, and message templates, but do not send messages or add API calls.',
    complexity: 'medium',
    icon: 'plug-zap',
    accentColor: 'fuchsia',
    previewType: 'integration-flow',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['personal-crm', 'booking-scheduler'] },
  },
];
