import type { BuildSuiteItem } from './types';

export const layoutItems: BuildSuiteItem[] = [
  {
    id: 'sidebar-workspace',
    label: 'Sidebar Workspace',
    category: 'Navigation',
    description: 'Persistent sidebar with primary routes and dense workspace content.',
    tags: ['sidebar', 'workspace', 'routes'],
    promptInstruction:
      'Use a sidebar workspace layout with persistent primary navigation, a compact top status area, and route-specific content panes.',
    complexity: 'medium',
  },
  {
    id: 'top-nav-dashboard',
    label: 'Top Nav Dashboard',
    category: 'Navigation',
    description: 'Header navigation with dashboard sections and responsive grids.',
    tags: ['top-nav', 'dashboard', 'responsive'],
    promptInstruction:
      'Use a top navigation dashboard layout with a branded header, primary route links, summary cards, and responsive content grids.',
    complexity: 'low',
  },
  {
    id: 'split-command-center',
    label: 'Split Command Center',
    category: 'Dashboard',
    description: 'Two-column command center with controls beside live results.',
    tags: ['split', 'controls', 'command-center'],
    promptInstruction:
      'Use a split command-center layout with inputs and controls on one side and live summaries, tables, or workflow results on the other.',
    complexity: 'medium',
  },
  {
    id: 'mobile-tabs',
    label: 'Mobile Tabs',
    category: 'Mobile',
    description: 'Mobile-first tabbed layout that scales into desktop panels.',
    tags: ['mobile', 'tabs', 'touch'],
    promptInstruction:
      'Use a mobile-first tabbed layout with touch-friendly tabs, stacked cards on small screens, and wider multi-column panels on desktop.',
    complexity: 'medium',
  },
  {
    id: 'bento-dashboard',
    label: 'Bento Dashboard',
    category: 'Dashboard',
    description: 'Modular dashboard blocks arranged as a polished bento grid.',
    tags: ['bento', 'dashboard', 'cards'],
    promptInstruction:
      'Use a bento dashboard layout with modular metric blocks, asymmetrical but stable grid areas, and clear responsive stacking.',
    complexity: 'medium',
  },
  {
    id: 'landing-page',
    label: 'Landing Page',
    category: 'Marketing',
    description: 'A strong first screen with direct entry into the app workflow.',
    tags: ['landing', 'hero', 'cta'],
    promptInstruction:
      'Use a landing-page layout with a polished first screen, clear primary calls-to-action, and visible links into the real app routes.',
    complexity: 'medium',
  },
  {
    id: 'admin-dashboard',
    label: 'Admin Dashboard',
    category: 'Dashboard',
    description: 'Operational admin layout with metrics, management lists, and controls.',
    tags: ['admin', 'dashboard', 'management'],
    promptInstruction:
      'Use an admin dashboard layout with summary metrics, management tables, filters, action panels, and clear operational navigation.',
    complexity: 'medium',
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-dashboard',
    badges: ['Enterprise', 'Popular'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'ecommerce-admin', 'inventory-manager'] },
  },
  {
    id: 'crm-layout',
    label: 'CRM',
    category: 'Workspace',
    description: 'Relationship management workspace with records and pipeline context.',
    tags: ['crm', 'contacts', 'pipeline'],
    promptInstruction:
      'Use a CRM layout with contact records, account context, task follow-ups, pipeline stages, and fast search/filter surfaces.',
    complexity: 'high',
    icon: 'app-window',
    accentColor: 'blue',
    previewType: 'layout-sidebar',
    badges: ['Enterprise', 'Advanced'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: [
      'data-tables',
      'search-filters',
      'forms-crud',
      'kanban-board',
      'notifications',
    ],
    compatibleWith: { appTypes: ['personal-crm'] },
  },
  {
    id: 'analytics-layout',
    label: 'Analytics',
    category: 'Dashboard',
    description: 'Metric-first layout for charts, cohorts, and performance insights.',
    tags: ['analytics', 'metrics', 'charts'],
    promptInstruction:
      'Use an analytics layout with KPI rows, chart panels, segment controls, insight summaries, and drill-down-ready sections.',
    complexity: 'high',
    icon: 'chart',
    accentColor: 'emerald',
    previewType: 'component-charts',
    badges: ['Popular', 'Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['saas-dashboard', 'expense-tracker', 'ecommerce-admin'] },
  },
  {
    id: 'ecommerce-layout',
    label: 'Ecommerce',
    category: 'Commerce',
    description: 'Commerce management layout for products, orders, and customers.',
    tags: ['ecommerce', 'products', 'orders'],
    promptInstruction:
      'Use an ecommerce layout with product/order summaries, catalog management, customer context, promotion controls, and clear commerce KPIs.',
    complexity: 'high',
    icon: 'boxes',
    accentColor: 'amber',
    previewType: 'layout-dashboard',
    badges: ['Commerce', 'Advanced'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['ecommerce-admin', 'inventory-manager'] },
  },
  {
    id: 'portfolio-layout',
    label: 'Portfolio',
    category: 'Marketing',
    description: 'Showcase layout for work, case studies, and project highlights.',
    tags: ['portfolio', 'showcase', 'case-studies'],
    promptInstruction:
      'Use a portfolio layout with project showcases, case-study cards, featured work, and polished contact or inquiry sections.',
    complexity: 'medium',
    icon: 'app-window',
    accentColor: 'violet',
    previewType: 'layout-landing',
    badges: ['Premium'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['portfolio'] },
  },
  {
    id: 'social-feed',
    label: 'Social Feed',
    category: 'Content',
    description: 'Feed-based layout for updates, posts, reactions, and activity.',
    tags: ['feed', 'social', 'activity'],
    promptInstruction:
      'Use a social feed layout with activity cards, composer surfaces, reactions, filters, and responsive stacked content.',
    complexity: 'medium',
    icon: 'blocks',
    accentColor: 'fuchsia',
    previewType: 'component-cards',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['habit-tracker', 'portfolio', 'kanban-board'] },
  },
  {
    id: 'documentation-layout',
    label: 'Documentation',
    category: 'Content',
    description: 'Docs layout with navigation, article content, and search surfaces.',
    tags: ['docs', 'articles', 'navigation'],
    promptInstruction:
      'Use a documentation layout with side navigation, article-like content, code or detail blocks when relevant, search, and section anchors.',
    complexity: 'medium',
    icon: 'layout-dashboard',
    accentColor: 'slate',
    previewType: 'layout-sidebar',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['knowledge-base', 'saas-dashboard'] },
  },
  {
    id: 'knowledge-base-layout',
    label: 'Knowledge Base',
    category: 'Content',
    description: 'Support-centered layout for articles, categories, and answers.',
    tags: ['knowledge-base', 'support', 'search'],
    promptInstruction:
      'Use a knowledge base layout with searchable categories, article cards, popular topics, and clear support-oriented empty states.',
    complexity: 'medium',
    icon: 'search',
    accentColor: 'cyan',
    previewType: 'component-tables',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps', 'Production Ready'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['knowledge-base', 'saas-dashboard'] },
  },
  {
    id: 'mobile-first-layout',
    label: 'Mobile First',
    category: 'Mobile',
    description: 'Thumb-friendly mobile layout that scales up to desktop.',
    tags: ['mobile-first', 'responsive', 'touch'],
    promptInstruction:
      'Use a mobile-first layout with touch-friendly controls, stacked sections, compact navigation, and desktop expansion that preserves mobile ergonomics.',
    complexity: 'medium',
    icon: 'smartphone',
    accentColor: 'emerald',
    previewType: 'mobile-device',
    badges: ['Mobile Ready', 'Popular'],
    recommendedFor: ['Best for Mobile'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['fitness-tracker', 'habit-tracker', 'booking-scheduler'] },
  },
  {
    id: 'split-screen',
    label: 'Split Screen',
    category: 'Workspace',
    description: 'Side-by-side input and output areas for focused workflows.',
    tags: ['split', 'workspace', 'two-column'],
    promptInstruction:
      'Use a split-screen layout with primary controls on one side and live output, previews, or results on the other.',
    complexity: 'medium',
    icon: 'layout-dashboard',
    accentColor: 'blue',
    previewType: 'layout-split',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['expense-tracker', 'personal-crm', 'saas-dashboard'] },
  },
  {
    id: 'magazine-layout',
    label: 'Magazine',
    category: 'Content',
    description: 'Editorial grid layout for stories, updates, and curated content.',
    tags: ['magazine', 'editorial', 'content'],
    promptInstruction:
      'Use a magazine layout with editorial grids, featured stories, compact cards, and strong visual hierarchy for content-heavy apps.',
    complexity: 'medium',
    icon: 'app-window',
    accentColor: 'amber',
    previewType: 'layout-bento',
    badges: ['Premium'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['portfolio', 'knowledge-base'] },
  },
  {
    id: 'ide-layout',
    label: 'IDE Layout',
    category: 'Workspace',
    description: 'Developer-style layout with panes, trees, tabs, and consoles.',
    tags: ['ide', 'panes', 'developer'],
    promptInstruction:
      'Use an IDE-style layout with pane-based navigation, tabs, inspector panels, and compact developer-focused information density.',
    complexity: 'high',
    icon: 'blocks',
    accentColor: 'emerald',
    previewType: 'layout-sidebar',
    badges: ['Advanced', 'AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['saas-dashboard', 'knowledge-base'] },
  },
  {
    id: 'kanban-workspace',
    label: 'Kanban Workspace',
    category: 'Workflow',
    description: 'Board-first workspace with cards, columns, and quick filters.',
    tags: ['kanban', 'workspace', 'columns'],
    promptInstruction:
      'Use a kanban workspace layout with board columns, compact cards, stage counts, filters, and clear move-ready affordances.',
    complexity: 'high',
    icon: 'kanban',
    accentColor: 'fuchsia',
    previewType: 'component-kanban',
    badges: ['Popular', 'Advanced'],
    recommendedFor: ['Best for SaaS'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['kanban-board', 'personal-crm'] },
  },
];
