import type {
  BuildSuiteAccentColor,
  BuildSuiteEnhancedItem,
  BuildSuiteGenerationImpact,
  BuildSuiteIcon,
  BuildSuiteItem,
  BuildSuitePreviewType,
  BuildSuiteVisualMetadata,
} from './types';

const DEFAULT_METADATA: BuildSuiteVisualMetadata = {
  icon: 'boxes',
  accentColor: 'emerald',
  previewType: 'app-dashboard',
  badges: [],
  recommendedFor: [],
  popularity: 3,
  difficulty: 'medium',
  estimatedGenerationImpact: 'medium',
  relatedItemIds: [],
  featuredCollectionIds: [],
};

type MetadataPatch = Partial<BuildSuiteVisualMetadata>;

const metadataById: Record<string, MetadataPatch> = {
  'personal-crm': {
    icon: 'app-window',
    accentColor: 'blue',
    badges: ['Enterprise', 'Popular'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: [
      'data-tables',
      'search-filters',
      'forms-crud',
      'kanban-board',
      'notifications',
      'natural-language-search',
      'smart-summaries',
      'local-storage',
    ],
    featuredCollectionIds: ['most-popular', 'best-saas', 'production-ready'],
  },
  'fitness-tracker': {
    icon: 'app-window',
    accentColor: 'emerald',
    badges: ['Mobile Ready', 'Popular'],
    recommendedFor: ['Best for Mobile', 'Recommended for Beginners'],
    popularity: 5,
    relatedItemIds: ['charts-metrics', 'forms-crud', 'mobile-first', 'local-storage'],
    featuredCollectionIds: ['trending', 'best-mobile'],
  },
  'expense-tracker': {
    icon: 'app-window',
    accentColor: 'amber',
    badges: ['Popular'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 4,
    relatedItemIds: ['charts-metrics', 'data-tables', 'csv-export', 'local-storage'],
    featuredCollectionIds: ['trending', 'beginner', 'production-ready'],
  },
  'inventory-manager': {
    icon: 'app-window',
    accentColor: 'cyan',
    badges: ['Enterprise'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: ['data-tables', 'forms-crud', 'csv-export', 'mock-api-ready'],
    featuredCollectionIds: ['production-ready'],
  },
  'booking-scheduler': {
    icon: 'calendar',
    accentColor: 'violet',
    badges: ['Advanced'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: ['calendar-schedule', 'mobile-first', 'notifications', 'local-storage'],
    featuredCollectionIds: ['best-saas'],
  },
  'saas-dashboard': {
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    badges: ['AI Ready', 'Enterprise'],
    recommendedFor: ['Best for SaaS', 'Best for AI Apps'],
    popularity: 5,
    relatedItemIds: ['charts-metrics', 'data-tables', 'smart-summaries', 'mock-api-ready'],
    featuredCollectionIds: ['most-popular', 'best-saas', 'best-ai', 'production-ready'],
  },
  'light-saas-blue': {
    icon: 'palette',
    accentColor: 'blue',
    previewType: 'palette-swatches',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['most-popular', 'best-saas'],
  },
  'light-emerald-office': {
    icon: 'palette',
    accentColor: 'emerald',
    previewType: 'palette-swatches',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['production-ready'],
  },
  'light-warm-product': {
    icon: 'palette',
    accentColor: 'amber',
    previewType: 'palette-swatches',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['beginner'],
  },
  'dark-matrix-green': {
    icon: 'palette',
    accentColor: 'emerald',
    previewType: 'palette-swatches',
    badges: ['Popular', 'Matrix'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['trending', 'most-popular', 'production-ready'],
  },
  'dark-slate-cyan': {
    icon: 'palette',
    accentColor: 'cyan',
    previewType: 'palette-swatches',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['trending', 'most-popular', 'best-saas'],
  },
  'dark-purple-lime': {
    icon: 'palette',
    accentColor: 'lime',
    previewType: 'palette-swatches',
    badges: ['Bold'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['best-ai'],
  },
  'quiet-saas': {
    icon: 'wand',
    accentColor: 'blue',
    previewType: 'style-saas',
    badges: ['Enterprise', 'Production Ready'],
    recommendedFor: ['Best for SaaS'],
    popularity: 5,
    difficulty: 'easy',
    relatedItemIds: ['data-tables', 'charts-metrics', 'top-nav-dashboard'],
    featuredCollectionIds: ['most-popular', 'best-saas', 'production-ready'],
  },
  'editorial-product': {
    icon: 'wand',
    accentColor: 'amber',
    previewType: 'style-apple',
    badges: ['Premium'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    relatedItemIds: ['landing-page', 'animated-gradients', 'soft-shadows'],
  },
  'operational-dashboard': {
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-dashboard',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    relatedItemIds: ['data-tables', 'charts-metrics', 'sidebar-workspace'],
    featuredCollectionIds: ['best-saas', 'production-ready'],
  },
  'mobile-app-polish': {
    icon: 'smartphone',
    accentColor: 'emerald',
    previewType: 'mobile-device',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    relatedItemIds: ['mobile-first', 'bottom-mobile-nav', 'minimal-motion'],
    featuredCollectionIds: ['best-mobile'],
  },
  glassmorphism: {
    icon: 'sparkles',
    accentColor: 'cyan',
    previewType: 'style-glass',
    badges: ['Trending', 'Premium'],
    recommendedFor: ['Best for SaaS', 'Best for AI Apps'],
    popularity: 5,
    relatedItemIds: ['floating-cards', 'blur-navigation', 'soft-shadows', 'animated-gradients'],
    featuredCollectionIds: ['trending', 'best-saas', 'best-ai'],
  },
  cyberpunk: {
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'style-cyber',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    relatedItemIds: ['animated-gradients', 'expressive-motion', 'dark-purple-lime'],
    featuredCollectionIds: ['best-ai'],
  },
  'apple-inspired': {
    icon: 'sparkles',
    accentColor: 'blue',
    previewType: 'style-apple',
    badges: ['Premium', 'Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    relatedItemIds: ['soft-shadows', 'mobile-first', 'minimal-motion'],
    featuredCollectionIds: ['best-mobile'],
  },
  material: {
    icon: 'component',
    accentColor: 'blue',
    previewType: 'style-material',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 4,
    difficulty: 'easy',
    relatedItemIds: ['forms-crud', 'data-tables', 'responsive-web'],
    featuredCollectionIds: ['beginner'],
  },
  fluent: {
    icon: 'component',
    accentColor: 'cyan',
    previewType: 'style-fluent',
    badges: ['Enterprise'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    relatedItemIds: ['data-tables', 'auth-shell', 'quiet-saas'],
    featuredCollectionIds: ['production-ready'],
  },
  'matrix-interface': {
    icon: 'zap',
    accentColor: 'emerald',
    previewType: 'style-matrix',
    badges: ['Matrix', 'Popular'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 5,
    relatedItemIds: ['dark-matrix-green', 'minimal-motion', 'smart-summaries'],
    featuredCollectionIds: ['trending', 'best-ai'],
  },
  'sidebar-workspace': {
    icon: 'layout-dashboard',
    accentColor: 'emerald',
    previewType: 'layout-sidebar',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    relatedItemIds: ['data-tables', 'auth-shell', 'quiet-saas'],
    featuredCollectionIds: ['best-saas', 'production-ready'],
  },
  'top-nav-dashboard': {
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-top-nav',
    badges: ['Popular'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 5,
    difficulty: 'easy',
    relatedItemIds: ['charts-metrics', 'data-tables', 'responsive-web'],
    featuredCollectionIds: ['most-popular', 'beginner'],
  },
  'split-command-center': {
    icon: 'layout-dashboard',
    accentColor: 'violet',
    previewType: 'layout-split',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    relatedItemIds: ['smart-summaries', 'forms-crud', 'charts-metrics'],
    featuredCollectionIds: ['best-ai'],
  },
  'mobile-tabs': {
    icon: 'smartphone',
    accentColor: 'emerald',
    previewType: 'layout-bottom-nav',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    relatedItemIds: ['mobile-first', 'minimal-motion', 'responsive-web'],
    featuredCollectionIds: ['best-mobile'],
  },
  'bento-dashboard': {
    icon: 'layout-dashboard',
    accentColor: 'fuchsia',
    previewType: 'layout-bento',
    badges: ['Trending'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    relatedItemIds: ['charts-metrics', 'floating-cards', 'soft-shadows'],
    featuredCollectionIds: ['trending', 'best-saas'],
  },
  'landing-page': {
    icon: 'app-window',
    accentColor: 'amber',
    previewType: 'layout-landing',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    relatedItemIds: ['editorial-product', 'animated-gradients', 'responsive-web'],
    featuredCollectionIds: ['production-ready'],
  },
  'data-tables': {
    icon: 'table',
    accentColor: 'cyan',
    previewType: 'component-tables',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS', 'Production Ready'],
    popularity: 5,
    relatedItemIds: ['search-filters', 'csv-export', 'forms-crud'],
    featuredCollectionIds: ['most-popular', 'best-saas', 'production-ready'],
  },
  'charts-metrics': {
    icon: 'chart',
    accentColor: 'emerald',
    previewType: 'component-charts',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 5,
    relatedItemIds: ['saas-dashboard', 'operational-dashboard', 'dashboard-motion'],
    featuredCollectionIds: ['most-popular', 'best-saas'],
  },
  'forms-crud': {
    icon: 'form',
    accentColor: 'blue',
    previewType: 'component-forms',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: ['data-tables', 'search-filters', 'local-storage'],
    featuredCollectionIds: ['most-popular', 'production-ready'],
  },
  'calendar-schedule': {
    icon: 'calendar',
    accentColor: 'violet',
    previewType: 'component-calendar',
    badges: ['Advanced'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    difficulty: 'advanced',
    relatedItemIds: ['booking-scheduler', 'notifications', 'mobile-first'],
    featuredCollectionIds: ['best-mobile'],
  },
  'kanban-board': {
    icon: 'kanban',
    accentColor: 'fuchsia',
    previewType: 'component-kanban',
    badges: ['Popular', 'Advanced'],
    recommendedFor: ['Best for SaaS'],
    popularity: 5,
    difficulty: 'advanced',
    relatedItemIds: ['personal-crm', 'data-tables', 'notifications'],
    featuredCollectionIds: ['trending', 'best-saas'],
  },
  notifications: {
    icon: 'star',
    accentColor: 'amber',
    previewType: 'component-notifications',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    relatedItemIds: ['calendar-schedule', 'auth-shell', 'minimal-motion'],
    featuredCollectionIds: ['best-mobile'],
  },
  'floating-cards': {
    icon: 'blocks',
    accentColor: 'cyan',
    previewType: 'component-cards',
    badges: ['Premium'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    relatedItemIds: ['glassmorphism', 'soft-shadows', 'blur-navigation'],
    featuredCollectionIds: ['trending', 'best-saas'],
  },
  'blur-navigation': {
    icon: 'layout-dashboard',
    accentColor: 'cyan',
    previewType: 'layout-top-nav',
    badges: ['Premium'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    relatedItemIds: ['glassmorphism', 'floating-cards', 'soft-shadows'],
    featuredCollectionIds: ['trending'],
  },
  'soft-shadows': {
    icon: 'sparkles',
    accentColor: 'blue',
    previewType: 'component-cards',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 4,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    relatedItemIds: ['apple-inspired', 'floating-cards', 'minimal-motion'],
    featuredCollectionIds: ['beginner'],
  },
  'search-filters': {
    icon: 'search',
    accentColor: 'emerald',
    previewType: 'component-tables',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 5,
    relatedItemIds: ['data-tables', 'forms-crud', 'natural-language-search'],
    featuredCollectionIds: ['most-popular', 'production-ready'],
  },
  'smart-summaries': {
    icon: 'brain-circuit',
    accentColor: 'fuchsia',
    previewType: 'ai-assistant',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 5,
    relatedItemIds: ['natural-language-search', 'draft-assistant', 'saas-dashboard'],
    featuredCollectionIds: ['trending', 'best-ai'],
  },
  'natural-language-search': {
    icon: 'search',
    accentColor: 'cyan',
    previewType: 'ai-assistant',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 5,
    relatedItemIds: ['smart-summaries', 'search-filters', 'data-tables'],
    featuredCollectionIds: ['best-ai'],
  },
  'draft-assistant': {
    icon: 'brain-circuit',
    accentColor: 'violet',
    previewType: 'ai-assistant',
    badges: ['AI Ready'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    relatedItemIds: ['smart-summaries', 'personal-crm', 'notifications'],
    featuredCollectionIds: ['best-ai'],
  },
  'local-storage': {
    icon: 'plug-zap',
    accentColor: 'emerald',
    previewType: 'integration-flow',
    badges: ['Production Ready'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 5,
    difficulty: 'easy',
    relatedItemIds: ['forms-crud', 'csv-export', 'responsive-web'],
    featuredCollectionIds: ['beginner', 'production-ready'],
  },
  'csv-export': {
    icon: 'plug-zap',
    accentColor: 'amber',
    previewType: 'integration-flow',
    badges: ['Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    relatedItemIds: ['data-tables', 'expense-tracker', 'inventory-manager'],
    featuredCollectionIds: ['production-ready'],
  },
  'mock-api-ready': {
    icon: 'plug-zap',
    accentColor: 'blue',
    previewType: 'integration-flow',
    badges: ['Enterprise'],
    recommendedFor: ['Production Ready'],
    popularity: 4,
    relatedItemIds: ['data-tables', 'auth-shell', 'saas-dashboard'],
    featuredCollectionIds: ['production-ready'],
  },
  'auth-shell': {
    icon: 'badge-check',
    accentColor: 'violet',
    previewType: 'integration-flow',
    badges: ['Enterprise'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    difficulty: 'easy',
    relatedItemIds: ['quiet-saas', 'sidebar-workspace', 'notifications'],
    featuredCollectionIds: ['best-saas'],
  },
  'minimal-motion': {
    icon: 'zap',
    accentColor: 'emerald',
    previewType: 'animation-motion',
    badges: ['Easy'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['beginner', 'production-ready'],
  },
  'dashboard-motion': {
    icon: 'zap',
    accentColor: 'cyan',
    previewType: 'animation-motion',
    badges: ['Popular'],
    recommendedFor: ['Best for SaaS'],
    popularity: 4,
    relatedItemIds: ['charts-metrics', 'operational-dashboard', 'floating-cards'],
    featuredCollectionIds: ['best-saas'],
  },
  'expressive-motion': {
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'animation-motion',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: ['cyberpunk', 'animated-gradients', 'bento-dashboard'],
    featuredCollectionIds: ['best-ai'],
  },
  'animated-gradients': {
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'animation-motion',
    badges: ['Trending'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    relatedItemIds: ['glassmorphism', 'expressive-motion', 'cyberpunk'],
    featuredCollectionIds: ['trending', 'best-ai'],
  },
  'responsive-web': {
    icon: 'smartphone',
    accentColor: 'blue',
    previewType: 'mobile-device',
    badges: ['Production Ready'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    featuredCollectionIds: ['beginner', 'production-ready'],
  },
  'mobile-first': {
    icon: 'smartphone',
    accentColor: 'emerald',
    previewType: 'mobile-device',
    badges: ['Mobile Ready'],
    recommendedFor: ['Best for Mobile'],
    popularity: 5,
    relatedItemIds: ['mobile-tabs', 'mobile-app-polish', 'minimal-motion'],
    featuredCollectionIds: ['most-popular', 'best-mobile'],
  },
  'capacitor-ready': {
    icon: 'smartphone',
    accentColor: 'lime',
    previewType: 'mobile-device',
    badges: ['Mobile Ready', 'Advanced'],
    recommendedFor: ['Best for Mobile'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    relatedItemIds: ['mobile-first', 'responsive-web', 'minimal-motion'],
    featuredCollectionIds: ['best-mobile'],
  },
};

function categoryDefaults(item: BuildSuiteItem): MetadataPatch {
  const categoryText = `${item.category} ${item.tags.join(' ')}`.toLowerCase();
  let icon: BuildSuiteIcon = 'boxes';
  let previewType: BuildSuitePreviewType = 'app-dashboard';
  let accentColor: BuildSuiteAccentColor = 'emerald';
  let estimatedGenerationImpact: BuildSuiteGenerationImpact = 'medium';

  if (categoryText.includes('light') || categoryText.includes('dark')) {
    icon = 'palette';
    previewType = 'palette-swatches';
  } else if (categoryText.includes('layout') || categoryText.includes('navigation')) {
    icon = 'layout-dashboard';
    previewType = 'layout-dashboard';
  } else if (categoryText.includes('mobile')) {
    icon = 'smartphone';
    previewType = 'mobile-device';
  } else if (categoryText.includes('ai') || categoryText.includes('assistant')) {
    icon = 'brain-circuit';
    previewType = 'ai-assistant';
    accentColor = 'fuchsia';
  } else if (categoryText.includes('integration') || categoryText.includes('api')) {
    icon = 'plug-zap';
    previewType = 'integration-flow';
  } else if (categoryText.includes('animation') || categoryText.includes('motion')) {
    icon = 'zap';
    previewType = 'animation-motion';
  } else if (categoryText.includes('table')) {
    icon = 'table';
    previewType = 'component-tables';
  }

  if (item.complexity === 'high') estimatedGenerationImpact = 'high';
  if (item.complexity === 'low') estimatedGenerationImpact = 'low';

  return {
    icon,
    accentColor,
    previewType,
    estimatedGenerationImpact,
    difficulty:
      item.complexity === 'high'
        ? 'advanced'
        : item.complexity === 'low'
          ? 'easy'
          : 'medium',
  };
}

export function enhanceBuildSuiteItem(item: BuildSuiteItem): BuildSuiteEnhancedItem {
  const metadata = {
    ...DEFAULT_METADATA,
    ...categoryDefaults(item),
    ...metadataById[item.id],
    ...item,
  };

  return {
    ...item,
    ...metadata,
    badges: metadata.badges ?? [],
    recommendedFor: metadata.recommendedFor ?? [],
    popularity: Math.min(5, Math.max(1, metadata.popularity ?? 3)),
    relatedItemIds: metadata.relatedItemIds ?? [],
    featuredCollectionIds: metadata.featuredCollectionIds ?? [],
  };
}

export function enhanceBuildSuiteItems(
  items: BuildSuiteItem[]
): BuildSuiteEnhancedItem[] {
  return items.map(enhanceBuildSuiteItem);
}
