import type { BuildSuiteItem } from './types';

export const styleItems: BuildSuiteItem[] = [
  {
    id: 'quiet-saas',
    label: 'Quiet SaaS',
    category: 'Product',
    description: 'Restrained, dense, and work-focused interface styling.',
    tags: ['saas', 'professional', 'dense'],
    promptInstruction:
      'Use quiet SaaS styling: compact navigation, restrained cards, clear labels, dense but readable data areas, and minimal decoration.',
    complexity: 'low',
  },
  {
    id: 'editorial-product',
    label: 'Editorial Product',
    category: 'Product',
    description: 'Large typography and polished content-led sections.',
    tags: ['editorial', 'marketing', 'polished'],
    promptInstruction:
      'Use editorial product styling with strong typography, generous spacing, and polished sections while keeping the app itself usable.',
    complexity: 'medium',
  },
  {
    id: 'operational-dashboard',
    label: 'Operational Dashboard',
    category: 'Dashboard',
    description: 'Charts, tables, status chips, and scannable control panels.',
    tags: ['dashboard', 'tables', 'charts'],
    promptInstruction:
      'Use operational dashboard styling with metric cards, tables, filters, status chips, and clear data hierarchy.',
    complexity: 'medium',
  },
  {
    id: 'mobile-app-polish',
    label: 'Mobile App Polish',
    category: 'Mobile',
    description: 'App-like spacing, bottom-safe actions, and touch-friendly controls.',
    tags: ['mobile', 'touch', 'app'],
    promptInstruction:
      'Use mobile-app polish with touch-friendly controls, strong spacing, sticky actions where useful, and responsive mobile-first layout.',
    complexity: 'medium',
  },
  {
    id: 'glassmorphism',
    label: 'Glassmorphism',
    category: 'Premium',
    description: 'Layered translucent surfaces, soft blur, and floating depth.',
    tags: ['glass', 'blur', 'premium', 'floating'],
    promptInstruction:
      'Use glassmorphism styling with translucent panels, subtle backdrop blur, floating cards, soft borders, and strong text contrast.',
    complexity: 'medium',
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    category: 'Expressive',
    description: 'High-energy neon contrast with sharp futuristic interface details.',
    tags: ['cyberpunk', 'neon', 'futuristic'],
    promptInstruction:
      'Use cyberpunk styling with restrained neon accents, high-contrast dark surfaces, sharp interface details, and readable controls.',
    complexity: 'high',
  },
  {
    id: 'apple-inspired',
    label: 'Apple Inspired',
    category: 'Premium',
    description: 'Soft minimal surfaces, calm hierarchy, and refined product polish.',
    tags: ['apple', 'minimal', 'premium'],
    promptInstruction:
      'Use Apple-inspired styling with soft surfaces, generous spacing, refined typography, careful hierarchy, and elegant controls.',
    complexity: 'medium',
  },
  {
    id: 'material',
    label: 'Material',
    category: 'System',
    description: 'Familiar elevation, clear actions, and structured component rhythm.',
    tags: ['material', 'system', 'elevation'],
    promptInstruction:
      'Use Material-inspired styling with clear elevation, familiar component rhythm, accessible buttons, and structured forms.',
    complexity: 'low',
  },
  {
    id: 'fluent',
    label: 'Fluent',
    category: 'System',
    description: 'Enterprise-friendly panels with subtle depth and clean controls.',
    tags: ['fluent', 'enterprise', 'system'],
    promptInstruction:
      'Use Fluent-inspired styling with clean enterprise panels, subtle depth, practical controls, and consistent spacing.',
    complexity: 'medium',
  },
  {
    id: 'matrix-interface',
    label: 'Matrix Interface',
    category: 'Matrix',
    description: 'Terminal-inspired command surfaces with luminous system feedback.',
    tags: ['matrix', 'terminal', 'command'],
    promptInstruction:
      'Use Matrix interface styling with terminal-inspired surfaces, luminous borders, compact controls, and precise system feedback.',
    complexity: 'medium',
  },
  {
    id: 'neo-brutalism',
    label: 'Neo Brutalism',
    category: 'Expressive',
    description: 'Bold borders, direct typography, and deliberately punchy surfaces.',
    tags: ['brutalist', 'bold', 'expressive'],
    promptInstruction:
      'Use neo brutalist styling with bold borders, strong contrast, flat color blocks, direct typography, and intentionally chunky controls.',
    complexity: 'medium',
    icon: 'wand',
    accentColor: 'amber',
    previewType: 'style-saas',
    badges: ['Trending', 'Advanced'],
    recommendedFor: ['Best for AI Apps'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['kanban-board', 'portfolio', 'ecommerce-admin'] },
  },
  {
    id: 'skeuomorphic',
    label: 'Skeuomorphic',
    category: 'Premium',
    description: 'Tactile panels, physical affordances, and realistic control depth.',
    tags: ['skeuomorphic', 'tactile', 'depth'],
    promptInstruction:
      'Use tasteful skeuomorphic styling with tactile controls, soft inset depth, physical affordances, and restrained realism.',
    complexity: 'high',
    icon: 'sparkles',
    accentColor: 'amber',
    previewType: 'style-apple',
    badges: ['Premium', 'Advanced'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['booking-scheduler', 'portfolio', 'fitness-tracker'] },
  },
  {
    id: 'aurora',
    label: 'Aurora',
    category: 'Premium',
    description: 'Soft luminous gradients and calm atmospheric product surfaces.',
    tags: ['aurora', 'gradient', 'premium'],
    promptInstruction:
      'Use aurora styling with contained luminous gradients, soft color transitions, readable foreground panels, and calm premium polish.',
    complexity: 'medium',
    icon: 'sparkles',
    accentColor: 'fuchsia',
    previewType: 'style-glass',
    badges: ['Trending', 'Premium'],
    recommendedFor: ['Best for AI Apps', 'Best for SaaS'],
    popularity: 5,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['saas-dashboard', 'habit-tracker', 'portfolio'] },
  },
  {
    id: 'retro',
    label: 'Retro',
    category: 'Expressive',
    description: 'Vintage interface details with modern usability.',
    tags: ['retro', 'vintage', 'playful'],
    promptInstruction:
      'Use retro styling with vintage-inspired typography, tasteful color blocking, nostalgic details, and modern accessible layout.',
    complexity: 'medium',
    icon: 'palette',
    accentColor: 'amber',
    previewType: 'style-saas',
    badges: ['Popular'],
    recommendedFor: ['Recommended for Beginners'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['habit-tracker', 'portfolio', 'kanban-board'] },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    category: 'System',
    description: 'Quiet whitespace, precise typography, and very little decoration.',
    tags: ['minimal', 'clean', 'calm'],
    promptInstruction:
      'Use minimal styling with calm whitespace, precise typography, restrained color, and only the interface elements needed for the workflow.',
    complexity: 'low',
    icon: 'wand',
    accentColor: 'slate',
    previewType: 'style-apple',
    badges: ['Easy', 'Production Ready'],
    recommendedFor: ['Recommended for Beginners', 'Production Ready'],
    popularity: 5,
    difficulty: 'easy',
    estimatedGenerationImpact: 'low',
    compatibleWith: { appTypes: ['personal-crm', 'expense-tracker', 'booking-scheduler'] },
  },
  {
    id: 'luxury',
    label: 'Luxury',
    category: 'Premium',
    description: 'Elegant spacing, refined contrast, and high-end brand polish.',
    tags: ['luxury', 'premium', 'brand'],
    promptInstruction:
      'Use luxury styling with refined typography, generous spacing, elegant contrast, and premium brand cues without sacrificing usability.',
    complexity: 'medium',
    icon: 'sparkles',
    accentColor: 'amber',
    previewType: 'style-apple',
    badges: ['Premium'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['portfolio', 'ecommerce-admin', 'booking-scheduler'] },
  },
  {
    id: 'fintech',
    label: 'Fintech',
    category: 'Industry',
    description: 'Trustworthy financial dashboards with precise numbers and status color.',
    tags: ['fintech', 'finance', 'trust'],
    promptInstruction:
      'Use fintech styling with precise numeric hierarchy, trustworthy surfaces, positive and negative states, and secure-feeling interaction patterns.',
    complexity: 'medium',
    icon: 'chart',
    accentColor: 'emerald',
    previewType: 'component-charts',
    badges: ['Enterprise', 'Fintech'],
    recommendedFor: ['Production Ready', 'Best for SaaS'],
    popularity: 4,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['expense-tracker', 'saas-dashboard', 'ecommerce-admin'] },
  },
  {
    id: 'medical',
    label: 'Medical',
    category: 'Industry',
    description: 'Calm clinical interfaces for scheduling, health, and records.',
    tags: ['medical', 'health', 'clinical'],
    promptInstruction:
      'Use medical styling with calm clinical surfaces, accessible contrast, clear statuses, careful spacing, and trustworthy data presentation.',
    complexity: 'medium',
    icon: 'badge-check',
    accentColor: 'cyan',
    previewType: 'style-fluent',
    badges: ['Enterprise', 'Production Ready'],
    recommendedFor: ['Production Ready'],
    popularity: 3,
    difficulty: 'medium',
    estimatedGenerationImpact: 'medium',
    compatibleWith: { appTypes: ['booking-scheduler', 'habit-tracker', 'personal-crm'] },
  },
  {
    id: 'gaming',
    label: 'Gaming',
    category: 'Expressive',
    description: 'Energetic panels, progress systems, and playful visual feedback.',
    tags: ['gaming', 'playful', 'progress'],
    promptInstruction:
      'Use gaming-inspired styling with energetic panels, progress feedback, badges, score-like metrics, and readable high-contrast controls.',
    complexity: 'high',
    icon: 'zap',
    accentColor: 'fuchsia',
    previewType: 'style-cyber',
    badges: ['Advanced'],
    recommendedFor: ['Best for AI Apps', 'Best for Mobile'],
    popularity: 4,
    difficulty: 'advanced',
    estimatedGenerationImpact: 'high',
    compatibleWith: { appTypes: ['fitness-tracker', 'habit-tracker', 'kanban-board'] },
  },
];
